# Generated by Django 4.2.3 on 2023-07-15 17:30

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('report_by', models.CharField(max_length=255)),
                ('date', models.IntegerField()),
                ('description', django_summernote.fields.SummernoteTextField()),
                ('conclusion', models.CharField(max_length=255)),
                ('like_count', models.IntegerField()),
                ('dislike_count', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
