# Generated by Django 4.2.3 on 2023-07-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_news_cover_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cover_tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
