# Generated by Django 4.2.3 on 2023-07-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_news_cover_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cover_tags',
        ),
    ]
