# Generated by Django 4.2.3 on 2023-07-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_news_dislike_news_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
