# Generated by Django 4.2.3 on 2023-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='editorial_pick',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
