# Generated by Django 4.2.3 on 2023-07-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
